name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.13']

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: lakehouse
          POSTGRES_USER: lakehouse
          POSTGRES_PASSWORD: lakehouse
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U lakehouse -d lakehouse"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: lakehouse
      DB_USER: lakehouse
      DB_PASSWORD: lakehouse

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup (deps)
        run: |
          make setup

      - name: Lint
        run: |
          .venv/bin/python -m ruff --version
          make lint

      - name: Migrate & Seed DB
        run: |
          make db-migrate
          make db-seed


      - name: Run tests
        run: |
          make test-all

          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform validate and test
        run: make terraform-validate
