name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: lakehouse
          POSTGRES_USER: lakehouse
          POSTGRES_PASSWORD: lakehouse
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U lakehouse -d lakehouse"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: lakehouse
      DB_USER: lakehouse
      DB_PASSWORD: lakehouse

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup (deps)
        run: |
          make setup

      - name: Lint
        run: |
          make lint

      - name: Migrate DB
        run: |
          make db-migrate

      - name: Seed DB for smoke tests
        run: |
          make db-seed

      - name: Pipeline smoke
        run: |
          make smoke

      - name: Run tests
        run: |
          make test